//
// Created by shecannotsee on 2022/10/9.
//

#ifndef VLPT_TEST_TEST_SHETHREADPOOL_TEST_VARIABLELENGTHPARAMETERTEMPLATE_SRC_TEMP_H_
#define VLPT_TEST_TEST_SHETHREADPOOL_TEST_VARIABLELENGTHPARAMETERTEMPLATE_SRC_TEMP_H_



namespace method1 {

void main() {

}

};//namespace method1

#endif //VLPT_TEST_TEST_SHETHREADPOOL_TEST_VARIABLELENGTHPARAMETERTEMPLATE_SRC_TEMP_H_
